name: Python CI

on:
  pull_request:
    branches:
      - main  # Ejecutar en pull requests hacia la rama main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Versión de Python que necesitas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias

    - name: Run all tests
      run: pytest tests/  # Ejecuta todas las pruebas dentro de la carpeta 'tests/'

#    - name: Run unit tests
#      run: pytest tests/Unit/  # Ejecuta solo las pruebas unitarias

#    - name: Run integration tests
#      run: pytest tests/Integration/  # Ejecuta solo las pruebas de integración

#    - name: Run e2e tests
#      run: pytest tests/e2e/  # Ejecuta solo las pruebas e2e