name: Run Tests

on:
  push:
    branches:
      - feature/add-tests
  pull_request:
    branches:
      - feature/add-tests

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Services
      run: |
        echo "Waiting for PostgreSQL..."
        while ! pg_isready -U test_user -h localhost -p 5432; do sleep 1; done
        echo "Waiting for MongoDB..."
        while ! mongo --eval "db.adminCommand({ ping: 1 })"; do sleep 1; done

    - name: Run Tests
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        MONGO_URI: mongodb://localhost:27017/test_todolist
      run: |
        pytest --disable-warnings