name: Run Tests

on:
  push:
    branches:
      - feature/add_tests
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        options: --health-cmd "curl --silent --fail localhost:27017 || exit 1" --health-interval 10s --health-timeout 5s --health-retries 3
      postgres:
        image: postgres:latest
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 3
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          FLASK_ENV: testing
          MONGO_URI: mongodb://localhost:27017/test_todolist
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        run: |
          pytest --maxfail=1 --disable-warnings -q
