name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  # Job para pruebas unitarias e integración
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit and Integration Tests
        run: |
          pytest --disable-warnings
        continue-on-error: true

  # Job para las pruebas E2E, que depende de que 'test' se ejecute primero
  e2e_tests:
    runs-on: ubuntu-latest
    needs: test  # Aseguramos que 'e2e_tests' dependa de 'test'

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run E2E Tests
        run: |
          pytest --disable-warnings
        env:
          DISPLAY: ":99.0"  # Selenium without interface