name: Run Tests

on:
  push:
    branches:
      - feature/add-tests
  pull_request:
    branches:
      - feature/add-tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo systemctl start postgresql
        sudo -u postgres psql -c "CREATE USER test_user WITH PASSWORD 'test_password';"
        sudo -u postgres psql -c "CREATE DATABASE test_db OWNER test_user;"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE test_db TO test_user;"

    - name: Install MongoDB
      run: |
        sudo apt-get update
        sudo apt-get install -y mongodb
        sudo systemctl start mongodb
        mongo --eval "use test_todolist"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        MONGO_URI: mongodb://localhost:27017/test_todolist
      run: |
        pytest --disable-warnings