name: Python CI

on:
  pull_request:
    branches:
      - main  # Execute tests just when main branch pull

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias de tu proyecto
      
    # Omitimos las pruebas por ahora
    # - name: Run tests
    #   run: |
    #     pytest  # Aquí se ejecutarían las pruebas en el futuro
    #Próximo