name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  # Job para pruebas unitarias e integración
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium==4.27.1 webdriver-manager

      - name: Run Unit and Integration Tests
        run: |
          pytest --disable-warnings
        continue-on-error: true

  # Job para las pruebas E2E, que depende de que 'test' se ejecute primero
  e2e_tests:
    runs-on: ubuntu-latest
    needs: test  # Aseguramos que 'e2e_tests' dependa de 'test'

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        ports:
          - 4444:4444  # Exponer el puerto 4444 para las pruebas

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium==4.27.1 webdriver-manager

      - name: Wait for Selenium server
        run: |
          while ! nc -zv localhost 4444; do
            echo "Waiting for Selenium server to start..."
            sleep 1
          done

      - name: Run E2E Tests
        run: |
          pytest --disable-warnings
        env:
          DISPLAY: ":99.0"  # Usar Selenium sin interfaz gráfica
          SELENIUM_URL: "http://localhost:4444/wd/hub"  # URL de Selenium WebDriver
        continue-on-error: true