name: Python CI

on:
  pull_request:
    branches:
      - main  # Execute Pull Ruquests to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias

    - name: Run unit tests
      id: unit-tests
      run: |
        pytest tests/Unit/ || echo "Unit tests failed, continuing"
      continue-on-error: true  # Conitnue even if unit tests fail

    - name: Run integration tests
      id: integration-tests
      run: |
        pytest tests/Integration/ || echo "Integration tests failed, continuing"
      continue-on-error: true  # Continue even if integration tests fail

    - name: Run e2e tests
      id: e2e-tests
      run: |
        pytest tests/e2e/ || echo "E2E tests failed, continuing"
      continue-on-error: true  # Continue even if e2e tests fail

    - name: Check test results
      if: ${{ steps.unit-tests.outcome == 'failure' || steps.integration-tests.outcome == 'failure' || steps.e2e-tests.outcome == 'failure' }}
      run: exit 1