name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Install and Start PostgreSQL
    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo systemctl start postgresql
        psql -U postgres -c "CREATE USER test_user WITH PASSWORD 'test_password';"
        psql -U postgres -c "CREATE DATABASE test_db OWNER test_user;"

    # 5. Install and Start MongoDB
    - name: Install MongoDB
      run: |
        sudo apt-get install -y mongodb
        sudo systemctl start mongodb
        mongo --eval 'db.getSiblingDB("test_todolist").createCollection("dummy");'

    # 6. Run tests
    - name: Run Tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: pytest
